package pemesanan;

/**
 *
 * @author maula
 */
public class FormPemesananMinuman extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPemesananMinuman.class.getName());

    /**
     * Creates new form FormPemesananMinuman
     */
    public FormPemesananMinuman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbSedikitGula = new javax.swing.JRadioButton();
        rbTeh = new javax.swing.JRadioButton();
        rbJus = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cbUkuran = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rbKopi = new javax.swing.JRadioButton();
        rbTanpaGula = new javax.swing.JRadioButton();
        rbGulaNormal = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cbTopping = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        btnProses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM PEMESANAN MINUM");

        jLabel2.setText("Jenis Minuman:");

        buttonGroup2.add(rbSedikitGula);
        rbSedikitGula.setText("Sedikit Gula");
        rbSedikitGula.addActionListener(this::rbSedikitGulaActionPerformed);

        buttonGroup1.add(rbTeh);
        rbTeh.setText("Teh");
        rbTeh.addActionListener(this::rbTehActionPerformed);

        buttonGroup1.add(rbJus);
        rbJus.setText("Jus");
        rbJus.addActionListener(this::rbJusActionPerformed);

        jLabel3.setText("Ukuran Gelas:");

        cbUkuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));

        jLabel4.setText("Tingkat Gula:");

        buttonGroup1.add(rbKopi);
        rbKopi.setText("Kopi");
        rbKopi.addActionListener(this::rbKopiActionPerformed);

        buttonGroup2.add(rbTanpaGula);
        rbTanpaGula.setText("Tanpa Gula");
        rbTanpaGula.addActionListener(this::rbTanpaGulaActionPerformed);

        buttonGroup2.add(rbGulaNormal);
        rbGulaNormal.setText("Gula Normal");
        rbGulaNormal.addActionListener(this::rbGulaNormalActionPerformed);

        jLabel5.setText("Topping:");

        cbTopping.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanpa Topping", "Bubble", "Jelly", "Cream", "Keju", " " }));

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnProses.setText("Hitung Total");
        btnProses.addActionListener(this::btnProsesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbKopi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbTeh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbJus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbTanpaGula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbSedikitGula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbGulaNormal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProses)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbTeh)
                    .addComponent(rbJus)
                    .addComponent(rbKopi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbTanpaGula)
                    .addComponent(rbSedikitGula)
                    .addComponent(rbGulaNormal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbTopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(btnReset))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void rbSedikitGulaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void rbTehActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void rbJusActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void rbKopiActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void rbTanpaGulaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void rbGulaNormalActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Reset Radio Button Minuman dan Gula
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();

        // Reset Combo Box ke pilihan pertama (indeks 0)
        cbUkuran.setSelectedIndex(0);
        cbTopping.setSelectedIndex(0);
    }                                        

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // 1. Validasi Pemilihan Minuman
        String jenisMinuman = "";
        int hargaMinuman = 0;

        if (rbKopi.isSelected()) {
            jenisMinuman = "Kopi";
            hargaMinuman = 15000;
        } else if (rbTeh.isSelected()) {
            jenisMinuman = "Teh";
            hargaMinuman = 10000;
        } else if (rbJus.isSelected()) {
            jenisMinuman = "Jus";
            hargaMinuman = 18000;
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Pilih jenis minuman terlebih dahulu!", 
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Ambil Pilihan Ukuran Gelas
        String ukuran = (String) cbUkuran.getSelectedItem();
        int hargaUkuran = 0;
        if ("Medium".equals(ukuran)) hargaUkuran = 3000;
        else if ("Large".equals(ukuran)) hargaUkuran = 5000;

        // 3. Ambil Pilihan Tingkat Gula
        String tingkatGula = "Tidak dipilih";
        if (rbTanpaGula.isSelected()) tingkatGula = "Tanpa Gula";
        else if (rbSedikitGula.isSelected()) tingkatGula = "Sedikit Gula";
        else if (rbGulaNormal.isSelected()) tingkatGula = "Gula Normal";

        // 4. Ambil Pilihan Topping
        String topping = (String) cbTopping.getSelectedItem();
        int hargaTopping = 0;
        if (!"Tanpa Topping".equals(topping)) hargaTopping = 4000;

        // 5. Kalkulasi Total Bayar
        int totalBayar = hargaMinuman + hargaUkuran + hargaTopping;

        // 6. Cetak Struk
        String struk = "========== STRUK PEMESANAN ==========\n"
                + "Jenis Minuman : " + jenisMinuman + " (Rp " + hargaMinuman + ")\n"
                + "Ukuran Gelas  : " + ukuran + " (+Rp " + hargaUkuran + ")\n"
                + "Tingkat Gula  : " + tingkatGula + "\n"
                + "Topping       : " + topping + " (+Rp " + hargaTopping + ")\n"
                + "-------------------------------------\n"
                + "Total Bayar   : Rp " + totalBayar + "\n"
                + "=====================================";

        javax.swing.JOptionPane.showMessageDialog(this, struk, 
            "Struk Pemesanan Minuman", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPemesananMinuman().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbTopping;
    private javax.swing.JComboBox<String> cbUkuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rbGulaNormal;
    private javax.swing.JRadioButton rbJus;
    private javax.swing.JRadioButton rbKopi;
    private javax.swing.JRadioButton rbSedikitGula;
    private javax.swing.JRadioButton rbTanpaGula;
    private javax.swing.JRadioButton rbTeh;
    // End of variables declaration                   
}